services:
  - type: web
    name: kume
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_PATH
        value: /app/donnees/fitness_data.db
      - key: CORS_ORIGINS
        value: ""
